#este es un comentario
clave: valor 
fruta: manzana

items:
  - item1
  - item2
  - item3   

personas:
  nombre: roxs
  edad: 00
  habilidades:
    - devops
    - python 
    - mlops 

services:
  web:
    image: nginx
    ports:
      - 80:80
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


