kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-volume
  labels:
    app: grupo1
spec:
  storageClassName: local-storage   
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/grupo1/"
