kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  labels:
    app: grupo1
spec:
  storageClassName: local-storage    
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
