apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: ghcr.io/stefanprodan/podinfo:6.6.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "64m"
    ports:
      - containerPort: 9898
