apiVersion: v1
kind: Pod
metadata:
  name: wanderlust-back-pod
  labels:
    name: wanderlust
spec:
  containers:
  - name: wanderlustback
    image: roxsross12/wandelust:backend-1.0.0 
    env:
      - name: MONGODB_URI
        value: "mongodb://mongodb/wanderlust"
      - name: REDIS_URL
        value: redis:6379
    resources:
      limits:
        memory: "128Mi"
        cpu: "256m"
    ports:
      - containerPort: 5000
