apiVersion: v1
kind: Pod
metadata:
  name: wanderlust-front-pod
  labels:
    name: wanderlust
spec:
  containers:
  - name: wanderlustfront
    image: roxsross12/wandelust:frontend-1.0.0
    env:
      - name: VITE_API_PATH
        value: "http://localhost:5000" 
    resources:
      limits:
        memory: "128Mi"
        cpu: "256m"
    ports:
      - containerPort: 5173
