apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    name: wanderlust
spec:
  containers:
  - name: mongo
    image: mongo
    resources:
      limits:
        memory: "128Mi"
        cpu: "256m"
    volumeMounts:
      - name: mongo-storage
        mountPath: /data/db
    ports:
      - containerPort: 27017
  volumes:
    - name: mongo-storage
      emptyDir: {}